name: Auto Update Data

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: 깃허브 리포지토리 체크아웃
        uses: actions/checkout@v3

      - name: 데이터 생성 (예제)
        run: |
          TODAY=$(date +'%Y-%m-%d')
          mkdir -p "$TODAY"
          echo "1688 최신 인기 제품 데이터" > "$TODAY/data.txt"
          echo "✅ 데이터 파일이 생성되었습니다: $TODAY/data.txt"

      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/vangoghlike/gpt_auto_oversea_good_china.git
          git add .
          git commit -m "자동 업데이트 - $(date +'%Y-%m-%d')" || exit 0
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
