name: Auto Update Data

on:
  schedule:
    # 한국 시간 기준으로 00시에 실행되게 설정 (UTC 기준으로 15시)
    - cron: '0 15 * * *'  # 한국 시간 00시 = UTC 15시
  workflow_dispatch:  # 수동 실행도 가능

jobs:
  update-repo:
    runs-on: ubuntu-latest
    
    steps:
      # 1. GitHub 리포지토리 체크아웃
      - name: GitHub 리포지토리 체크아웃
        uses: actions/checkout@v3
        
      # 2. 데이터 생성 및 마크다운 파일 생성 (한국 시간 기준으로 날짜 설정)
      - name: 데이터 생성 (마크다운)
        run: |
          TODAY=$(TZ='Asia/Seoul' date +"%Y-%m-%d")  # 한국 시간 기준으로 날짜 설정
          mkdir -p "$TODAY"
          touch "$TODAY/.keep"  # Git에서 폴더 인식되게 더미 파일 생성
          echo "## 1688 최신 인기 제품 데이터 - $TODAY" > "$TODAY/data.md"
          echo "- 최신 제품 목록이 여기에 포함됩니다." >> "$TODAY/data.md"
        
      # 3. 변경 사항 커밋 및 푸시
      - name: 변경 사항 커밋 및 푸시
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "자동 업데이트 - $(date +"%Y-%m-%d")" || exit 0
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # GH_TOKEN 환경 변수 설정
